version: '3.8'

services:
  postgres_db:
    image: 'postgres:13.1-alpine'
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
#  app:
#    image: 'docker-spring-boot-postgres:latest'
#    ports:
#      - "8080:8080"
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - postgres_db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
#      - SPRING_DATASOURCE_USERNAME=compose-postgres
#      - SPRING_DATASOURCE_PASSWORD=compose-postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

